// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBqv5XHmsI1c-l0kKwMEabZX_QxFJkUPjg',
    appId: '1:329290060849:web:9895cfb23c995448c7f110',
    messagingSenderId: '329290060849',
    projectId: 'stories-app-2b65c',  // email nxtruong
    authDomain: 'stories-app-2b65c.firebaseapp.com',
    databaseURL: 'https://stories-app-2b65c-default-rtdb.firebaseio.com',
    storageBucket: 'stories-app-2b65c.firebasestorage.app',
    measurementId: 'G-GF99VMNDRL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCchTos0xrhbJvEVaudFyfaAJBMcQ2_UIw',
    appId: '1:329290060849:android:9c641f78932fc981c7f110',
    messagingSenderId: '329290060849',
    projectId: 'stories-app-2b65c',
    databaseURL: 'https://stories-app-2b65c-default-rtdb.firebaseio.com',
    storageBucket: 'stories-app-2b65c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDkc7Zn5QyHOWz9ur_GGViGCGZq7OPe94A',
    appId: '1:329290060849:ios:e72ae27a990bf86ec7f110',
    messagingSenderId: '329290060849',
    projectId: 'stories-app-2b65c',
    databaseURL: 'https://stories-app-2b65c-default-rtdb.firebaseio.com',
    storageBucket: 'stories-app-2b65c.firebasestorage.app',
    iosBundleId: 'com.example.clothingStore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDkc7Zn5QyHOWz9ur_GGViGCGZq7OPe94A',
    appId: '1:329290060849:ios:e72ae27a990bf86ec7f110',
    messagingSenderId: '329290060849',
    projectId: 'stories-app-2b65c',
    databaseURL: 'https://stories-app-2b65c-default-rtdb.firebaseio.com',
    storageBucket: 'stories-app-2b65c.firebasestorage.app',
    iosBundleId: 'com.example.clothingStore',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBqv5XHmsI1c-l0kKwMEabZX_QxFJkUPjg',
    appId: '1:329290060849:web:0a5e4fc6bd03bafcc7f110',
    messagingSenderId: '329290060849',
    projectId: 'stories-app-2b65c',
    authDomain: 'stories-app-2b65c.firebaseapp.com',
    databaseURL: 'https://stories-app-2b65c-default-rtdb.firebaseio.com',
    storageBucket: 'stories-app-2b65c.firebasestorage.app',
    measurementId: 'G-7303MJHEEE',
  );
}
