import 'package:cloud_firestore/cloud_firestore.dart';

Future<void> importProducts() async {
  final FirebaseFirestore firestore = FirebaseFirestore.instance;

  final List<Map<String, dynamic>> productsData = [
    // ===== ÁO PHÔNG =====
    {
      "name": "Áo Thun Oversize Basic",
      "category": "Áo Thun",
      "price": 299000,
      "imageAsset": "assets/images/products/ao_01.jpg",
      "description": "Áo thun oversize cotton cao cấp, mặc thoải mái, phù hợp mix nhiều kiểu.",
      "sizes": ["S", "M", "L", "XL"],
      "rating": 4.6,
      "sold": 1240,
      "stock": 150,
      "isAvailable": true,
      "createdAt": FieldValue.serverTimestamp(),
    },
    {
      "name": "Áo Thun Basic Tay Ngắn",
      "category": "Áo Thun",
      "price": 279000,
      "imageAsset": "assets/images/products/ao_02.jpg",
      "description": "Áo thun basic cổ tròn, chất cotton 100%, co giãn nhẹ, thấm hút tốt.",
      "sizes": ["S", "M", "L", "XL"],
      "rating": 4.5,
      "sold": 980,
      "stock": 200,
      "isAvailable": true,
      "createdAt": FieldValue.serverTimestamp(),
    },
    {
      "name": "Áo Thun Graphic Unisex",
      "category": "Áo Thun",
      "price": 320000,
      "imageAsset": "assets/images/products/ao_03.jpg",
      "description": "Áo thun in hình graphic phong cách streetwear, form rộng thoải mái.",
      "sizes": ["S", "M", "L", "XL"],
      "rating": 4.7,
      "sold": 760,
      "stock": 120,
      "isAvailable": true,
      "createdAt": FieldValue.serverTimestamp(),
    },
    {
      "name": "Áo Thun Polo Nam",
      "category": "Áo Thun",
      "price": 359000,
      "imageAsset": "assets/images/products/ao_04.jpg",
      "description": "Áo thun polo cổ bẻ, chất pique thoáng khí, phù hợp đi làm và đi chơi.",
      "sizes": ["M", "L", "XL"],
      "rating": 4.8,
      "sold": 890,
      "stock": 100,
      "isAvailable": true,
      "createdAt": FieldValue.serverTimestamp(),
    },

    // ===== QUẦN DÀI =====
    {
      "name": "Quần Jeans Slim Fit",
      "category": "Quần Dài",
      "price": 450000,
      "imageAsset": "assets/images/products/quan_01.jpg",
      "description": "Quần jeans slim fit co giãn tốt, form chuẩn, dễ phối đồ.",
      "sizes": ["28", "29", "30", "31", "32"],
      "rating": 4.7,
      "sold": 650,
      "stock": 90,
      "isAvailable": true,
      "createdAt": FieldValue.serverTimestamp(),
    },
    {
      "name": "Quần Kaki Straight",
      "category": "Quần Dài",
      "price": 399000,
      "imageAsset": "assets/images/products/quan_02.jpg",
      "description": "Quần kaki form thẳng, chất liệu cotton pha, phù hợp đi làm hoặc dạo phố.",
      "sizes": ["28", "29", "30", "31", "32"],
      "rating": 4.6,
      "sold": 540,
      "stock": 85,
      "isAvailable": true,
      "createdAt": FieldValue.serverTimestamp(),
    },
    {
      "name": "Quần Jogger Thể Thao",
      "category": "Quần Dài",
      "price": 350000,
      "imageAsset": "assets/images/products/quan_03.jpg",
      "description": "Quần jogger co giãn 4 chiều, cạp chun tiện lợi, phù hợp tập gym và mặc nhà.",
      "sizes": ["S", "M", "L", "XL"],
      "rating": 4.5,
      "sold": 720,
      "stock": 130,
      "isAvailable": true,
      "createdAt": FieldValue.serverTimestamp(),
    },
    {
      "name": "Quần Âu Slim Công Sở",
      "category": "Quần Dài",
      "price": 480000,
      "imageAsset": "assets/images/products/quan_04.jpg",
      "description": "Quần âu slim fit thanh lịch, chất liệu cao cấp ít nhăn, phù hợp môi trường công sở.",
      "sizes": ["28", "29", "30", "31", "32"],
      "rating": 4.8,
      "sold": 410,
      "stock": 75,
      "isAvailable": true,
      "createdAt": FieldValue.serverTimestamp(),
    },

    // ===== MŨ =====
    {
      "name": "Mũ Snapback Basic",
      "category": "Mũ",
      "price": 159000,
      "imageAsset": "assets/images/products/mu_01.jpg",
      "description": "Mũ snapback logo thêu nổi, khóa sau điều chỉnh được, phong cách streetwear.",
      "sizes": ["Free Size"],
      "rating": 4.5,
      "sold": 830,
      "stock": 200,
      "isAvailable": true,
      "createdAt": FieldValue.serverTimestamp(),
    },
    {
      "name": "Mũ Bucket Unisex",
      "category": "Mũ",
      "price": 179000,
      "imageAsset": "assets/images/products/mu_02.jpg",
      "description": "Mũ bucket vành tròn chống nắng tốt, chất cotton mềm, phù hợp nam và nữ.",
      "sizes": ["Free Size"],
      "rating": 4.6,
      "sold": 610,
      "stock": 180,
      "isAvailable": true,
      "createdAt": FieldValue.serverTimestamp(),
    },
    {
      "name": "Mũ Lưỡi Trai Dad Hat",
      "category": "Mũ",
      "price": 149000,
      "imageAsset": "assets/images/products/mu_03.jpg",
      "description": "Dad hat form cong mềm, dây điều chỉnh phía sau, tông màu trung tính dễ mix đồ.",
      "sizes": ["Free Size"],
      "rating": 4.4,
      "sold": 490,
      "stock": 160,
      "isAvailable": true,
      "createdAt": FieldValue.serverTimestamp(),
    },
    {
      "name": "Mũ Beanie Len Mùa Đông",
      "category": "Mũ",
      "price": 129000,
      "imageAsset": "assets/images/products/mu_04.jpg",
      "description": "Mũ beanie len dày giữ ấm, form ôm đầu thoải mái, màu sắc đa dạng.",
      "sizes": ["Free Size"],
      "rating": 4.7,
      "sold": 370,
      "stock": 140,
      "isAvailable": true,
      "createdAt": FieldValue.serverTimestamp(),
    },

    // ===== BALO =====
    {
      "name": "Balo Laptop 15.6 inch",
      "category": "Balo",
      "price": 599000,
      "imageAsset": "assets/images/products/bag_01.jpg",
      "description": "Balo chống sốc ngăn laptop 15.6\", chất liệu chống thấm nước, nhiều ngăn tiện dụng.",
      "sizes": ["One Size"],
      "rating": 4.8,
      "sold": 920,
      "stock": 70,
      "isAvailable": true,
      "createdAt": FieldValue.serverTimestamp(),
    },
    {
      "name": "Balo Thời Trang Mini",
      "category": "Balo",
      "price": 399000,
      "imageAsset": "assets/images/products/bag_02.jpg",
      "description": "Balo mini phong cách, dung tích vừa phải, phù hợp đi chơi và đi học.",
      "sizes": ["One Size"],
      "rating": 4.5,
      "sold": 670,
      "stock": 110,
      "isAvailable": true,
      "createdAt": FieldValue.serverTimestamp(),
    },
    {
      "name": "Balo Du Lịch 30L",
      "category": "Balo",
      "price": 750000,
      "imageAsset": "assets/images/products/bag_03.jpg",
      "description": "Balo du lịch dung tích 30L, khung lưng thoáng khí, quai đeo có đệm chống mỏi.",
      "sizes": ["One Size"],
      "rating": 4.7,
      "sold": 280,
      "stock": 60,
      "isAvailable": true,
      "createdAt": FieldValue.serverTimestamp(),
    },
    {
      "name": "Balo Streetwear Phản Quang",
      "category": "Balo",
      "price": 520000,
      "imageAsset": "assets/images/products/bag_04.jpg",
      "description": "Balo phong cách streetwear có chi tiết phản quang, ngăn chính rộng, khóa kéo chắc chắn.",
      "sizes": ["One Size"],
      "rating": 4.6,
      "sold": 350,
      "stock": 90,
      "isAvailable": true,
      "createdAt": FieldValue.serverTimestamp(),
    },

    // ===== DÉP =====
    {
      "name": "Dép Quai Ngang Đế Bằng",
      "category": "Dép",
      "price": 199000,
      "imageAsset": "assets/images/products/dep_01.jpg",
      "description": "Dép quai ngang đế EVA nhẹ, chống trơn trượt, phù hợp đi biển và dạo phố.",
      "sizes": ["38", "39", "40", "41", "42", "43"],
      "rating": 4.4,
      "sold": 1100,
      "stock": 250,
      "isAvailable": true,
      "createdAt": FieldValue.serverTimestamp(),
    },
    {
      "name": "Dép Slide Unisex",
      "category": "Dép",
      "price": 229000,
      "imageAsset": "assets/images/products/dep_02.jpg",
      "description": "Dép slide một quai logo thêu nổi, đế dày êm chân, phong cách tối giản.",
      "sizes": ["38", "39", "40", "41", "42", "43"],
      "rating": 4.6,
      "sold": 870,
      "stock": 220,
      "isAvailable": true,
      "createdAt": FieldValue.serverTimestamp(),
    },

    // ===== PHỤ KIỆN =====
    {
      "name": "Dây Chuyền bạc Nam",
      "category": "Phụ Kiện",
      "price": 189000,
      "imageAsset": "assets/images/products/phukien_01.jpg",
      "description": "Dây chuyền bạc, thiết kế tối giản, phù hợp mix với nhiều outfit.",
      "sizes": ["Free Size"],
      "rating": 4.6,
      "sold": 560,
      "stock": 180,
      "isAvailable": true,
      "createdAt": FieldValue.serverTimestamp(),
    },
    {
      "name": "Khuyên Tai Bạc 925",
      "category": "Phụ Kiện",
      "price": 149000,
      "imageAsset": "assets/images/products/phukien_02.jpg",
      "description": "Khuyên tai bạc 925 không gây dị ứng, thiết kế unisex đơn giản tinh tế.",
      "sizes": ["Free Size"],
      "rating": 4.7,
      "sold": 890,
      "stock": 250,
      "isAvailable": true,
      "createdAt": FieldValue.serverTimestamp(),
    },
  ];

  print("🔄 Bắt đầu import ${productsData.length} sản phẩm...");

  int successCount = 0;
  int errorCount = 0;

  for (var data in productsData) {
    try {
      await firestore.collection('products').add(data);
      print("✅ Đã thêm: ${data['name']}");
      successCount++;
    } catch (e) {
      print("❌ Lỗi khi thêm ${data['name']}: $e");
      errorCount++;
    }
  }

  print("🎉 Import hoàn tất! Thành công: $successCount | Lỗi: $errorCount");
}